FROM node:18-alpine

WORKDIR /app

COPY vercel_client/package.json vercel_client/package-lock.json* ./
RUN npm install

COPY vercel_client/ .

RUN npm run build

ENV PORT=3000
EXPOSE 3000

CMD ["npm", "run", "start"]
