
FROM node:18-bullseye

# Install OS packages and vercel CLI
RUN apt-get update && apt-get install -y --no-install-recommends git curl bash ca-certificates \
	&& npm install -g vercel@latest \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /work

ENTRYPOINT ["/bin/sh","-c"]
